import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // --- PREMIUM TOKENS (PHASE 1) ---
        brand: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6", // Primary Accent
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        zinc: {
          50: "#fafafa",
          100: "#f4f4f5",
          200: "#e4e4e7",
          300: "#d4d4d8",
          400: "#a1a1aa",
          500: "#71717a",
          600: "#52525b",
          700: "#3f3f46",
          800: "#27272a",
          900: "#18181b",
          950: "#09090b",
        },
        // --- LEGACY TOKENS (Mapped to Premium CSS Variables for compatibility) ---
        surface: "var(--surface)",
        "surface-dim": "var(--surface)",
        "surface-bright": "var(--surface-container-high)",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "var(--surface-container)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-high)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-surface": "var(--on-surface)",
        "inverse-on-surface": "var(--surface)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        "surface-tint": "var(--primary)",
        primary: "var(--primary)",
        "on-primary": "#ffffff",
        "primary-container": "var(--primary-container)",
        "on-primary-container": "var(--on-surface)",
        "inverse-primary": "var(--primary)",
        secondary: "var(--secondary)",
        "on-secondary": "#ffffff",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-container": "var(--on-surface)",
        tertiary: "var(--tertiary)",
        "on-tertiary": "#000000",
        "tertiary-container": "rgba(34, 211, 238, 0.1)",
        "on-tertiary-container": "var(--on-surface)",
        error: "#f87171",
        "on-error": "#ffffff",
        "error-container": "rgba(248, 113, 113, 0.1)",
        "on-error-container": "#f87171",
        background: "var(--surface)",
        "on-background": "var(--on-surface)",
      },
      fontFamily: {
        display: ["var(--font-hanken)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      borderRadius: {
        xs: "0.25rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      boxShadow: {
        premium: "0 8px 32px rgba(0, 0, 0, 0.4)",
        "premium-deep": "0 20px 50px rgba(0, 0, 0, 0.5), 0 0 20px rgba(99, 102, 241, 0.05)",
        glow: "0 0 20px rgba(99, 102, 241, 0.2)",
        "glow-brand": "0 0 20px rgba(139, 92, 246, 0.3)",
      },
      backdropBlur: {
        xs: "4px",
        sm: "8px",
        DEFAULT: "20px",
        lg: "40px",
        xl: "60px",
      },
      animation: {
        "fade-in": "fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in": "slideIn 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
        "shimmer": "shimmer 2s infinite linear",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(-16px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "0.6" },
          "50%": { opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
