import React from 'react'
import { 
  Plus,
  PlusCircle,
  ImagePlus,
  Shield,
  ArrowLeft,
  ArrowRight,
  Bookmark,
  Briefcase,
  Calendar,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Check,
  CheckCircle,
  ChevronLeft,
  Ban,
  ChevronRight,
  X,
  Code2,
  LayoutDashboard,
  Trash2,
  FileText,
  Users,
  Building2,
  Download,
  Edit2,
  Trophy,
  AlertCircle,
  Heart,
  Drama,
  Rss,
  Upload,
  Scale,
  UserX,
  ShieldAlert,
  HelpCircle,
  Home,
  Network,
  Info,
  Flame,
  MapPin,
  Lock,
  Moon,
  LockOpen,
  LogOut,
  Mail,
  MailCheck,
  BookOpen,
  MoreVertical,
  Bell,
  Mic,
  Wrench,
  BellRing,
  ExternalLink,
  User,
  UserPlus,
  UserMinus,
  Image,
  Camera,
  Play,
  Brain,
  RefreshCw,
  Rocket,
  Save,
  Clock,
  GraduationCap,
  Search,
  SearchX,
  Tag,
  Send,
  Settings,
  Share2,
  Bot,
  Gamepad2,
  Star,
  Store,
  Headphones,
  ThumbsUp,
  Compass,
  UploadCloud,
  ShieldCheck,
  Eye,
  EyeOff,
  Hand,
  Layers,
  BarChart3,
  Coins,
  Smile,
  Activity,
  HeartCrack,
  FolderOpen,
  Handshake,
  Phone
} from 'lucide-react'

const MAPPING: Record<string, React.ComponentType<any>> = {
  // Math mapping keys
  'add': Plus,
  'add_circle': PlusCircle,
  'add_photo_alternate': ImagePlus,
  'admin_panel_settings': Shield,
  'arrow_back': ArrowLeft,
  'arrow_forward': ArrowRight,
  'bookmark': Bookmark,
  'business_center': Briefcase,
  'calendar_month': Calendar,
  'campaign': Megaphone,
  'chat': MessageCircle,
  'chat_bubble': MessageSquare,
  'chat_bubble_outline': MessageSquare,
  'check': Check,
  'check_circle': CheckCircle,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'close': X,
  'code': Code2,
  'dashboard': LayoutDashboard,
  'delete': Trash2,
  'description': FileText,
  'diversity_3': Users,
  'domain': Building2,
  'download': Download,
  'edit': Edit2,
  'emoji_events': Trophy,
  'error': AlertCircle,
  'event': Calendar,
  'favorite': Heart,
  'favorite_border': Heart,
  'feed': Rss,
  'file_upload': Upload,
  'forum': MessageSquare,
  'gavel': Scale,
  'group': Users,
  'group_add': UserPlus,
  'group_off': UserX,
  'groups': Users,
  'gpp_maybe': ShieldAlert,
  'help_outline': HelpCircle,
  'home': Home,
  'hub': Network,
  'info': Info,
  'local_fire_department': Flame,
  'location_on': MapPin,
  'lock': Lock,
  'lock_open': LockOpen,
  'logout': LogOut,
  'mail': Mail,
  'mark_email_read': MailCheck,
  'menu_book': BookOpen,
  'more_vert': MoreVertical,
  'notifications': Bell,
  'notifications_active': BellRing,
  'open_in_new': ExternalLink,
  'person': User,
  'person_add': UserPlus,
  'person_remove': UserMinus,
  'photo_library': Image,
  'photo_camera': Camera,
  'play_arrow': Play,
  'psychology': Brain,
  'refresh': RefreshCw,
  'rocket_launch': Rocket,
  'save': Save,
  'schedule': Clock,
  'school': GraduationCap,
  'search': Search,
  'search_off': SearchX,
  'security': Shield,
  'sell': Tag,
  'send': Send,
  'settings': Settings,
  'share': Share2,
  'smart_toy': Bot,
  'sports_esports': Gamepad2,
  'star': Star,
  'store': Store,
  'storefront': Store,
  'support_agent': Headphones,
  'thumb_up': ThumbsUp,
  'travel_explore': Compass,
  'upload': Upload,
  'upload_file': UploadCloud,
  'verified': CheckCircle,
  'verified_user': ShieldCheck,
  'visibility': Eye,
  'visibility_off': EyeOff,
  'waving_hand': Hand,
  'work_outline': Briefcase,
  'architecture': Layers,
  'bar_chart': BarChart3,
  'payments': Coins,
  'handshake': Handshake,
  'mood': Smile,
  'group_work': Activity,
  'heart_broken': HeartCrack,
  'theater_comedy': Drama,
  'sports': Trophy,
  'volunteer_activism': Heart,
  'work': Briefcase,
  'timer': Clock,
  'book_2': BookOpen,
  'calendar_today': Calendar,
  'badge': User,
  'apartment': Building2,
  'phone': Phone,
  'article': FileText,
  'edit_note': Edit2,
  'dark_mode': Moon,
  'mic': Mic,
  'build': Wrench,
  'account_balance': Building2,
  'block': Ban,
}

interface DynamicIconProps {
  name: string
  size?: number
  className?: string
  style?: React.CSSProperties
}

export function DynamicIcon({ name, size = 18, className, style }: DynamicIconProps) {
  const IconComponent = MAPPING[name] || HelpCircle
  return <IconComponent size={size} className={className} style={style} />
}
